export const ACTIONS = {
    SWITCHER: "SWITCHER",
    
    REMOVE_TO_DO: "REMOVE_TO_DO",
    ADD_TO_BASKET: "ADD_TO_BASKET",
    REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
    COUNT_REMOVE: "COUNT_REMOVE",
  };
  
  